from __future__ import annotations

import argparse
from pathlib import Path

from scripts.phase7_report import generate_phase7_report


def _field(label: str, value: str | None) -> str:
    return f"- {label}: {value or 'pending'}"


def build_phase7_log_draft(
    benchmark_run_path: str | Path,
    gpu_harden_path: str | Path,
    gpu_thresholds_path: str | Path,
    *,
    date: str | None = None,
    environment: str | None = None,
    backend: str | None = None,
    profile: str | None = None,
    workflow_run_url: str | None = None,
    artifact_location: str | None = None,
) -> str:
    report = generate_phase7_report(benchmark_run_path, gpu_harden_path, gpu_thresholds_path)

    lines: list[str] = []
    lines.append("# Phase 7 Results Log Draft")
    lines.append("")
    lines.append(
        "This draft is generated from the Phase 7 workflow artifacts. "
        "It is meant to be completed with live measurement evidence."
    )
    lines.append("")
    lines.append("## Run Metadata")
    lines.append(_field("Date", date))
    lines.append(_field("Environment", environment))
    lines.append(_field("Backend", backend))
    lines.append(_field("Profile", profile))
    lines.append(_field("Workflow run URL", workflow_run_url))
    lines.append(_field("Artifact location", artifact_location))
    lines.append("")
    lines.append("## Derived Snapshot")
    lines.append(report.rstrip())
    lines.append("")
    lines.append("## Live Measurement Notes")
    lines.append("- L3 profile: pending live measurement")
    lines.append("- Local L2 profile: pending live measurement")
    lines.append("- Attestation / research notes: pending live measurement")
    lines.append("")
    lines.append("## Decision Summary")
    lines.append("- Is the current CPU path good enough?: pending")
    lines.append("- Is deeper GPU work justified now?: pending")
    lines.append("- Should anything move from research to product?: pending")
    lines.append("")
    lines.append("## Attachments")
    lines.append(f"- `benchmark-run`: {benchmark_run_path}")
    lines.append(f"- `gpu-harden`: {gpu_harden_path}")
    lines.append(f"- `gpu-thresholds`: {gpu_thresholds_path}")
    lines.append("")
    lines.append("Generated by `scripts/phase7_prepare_log.py` from the workflow JSON artifacts.")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a prefilled Phase 7 results log draft from workflow artifacts.")
    parser.add_argument("--benchmark-run", required=True, help="Path to the benchmark-run JSON artifact.")
    parser.add_argument("--gpu-harden", required=True, help="Path to the gpu-harden JSON artifact.")
    parser.add_argument("--gpu-thresholds", required=True, help="Path to the gpu-thresholds JSON artifact.")
    parser.add_argument("--output", help="Optional markdown output path.")
    parser.add_argument("--date", help="Optional run date to prefill.")
    parser.add_argument("--environment", help="Optional environment label to prefill.")
    parser.add_argument("--backend", help="Optional backend label to prefill.")
    parser.add_argument("--profile", help="Optional profile label to prefill.")
    parser.add_argument("--workflow-run-url", help="Optional GitHub Actions run URL to prefill.")
    parser.add_argument("--artifact-location", help="Optional artifact location to prefill.")
    args = parser.parse_args()

    log_draft = build_phase7_log_draft(
        args.benchmark_run,
        args.gpu_harden,
        args.gpu_thresholds,
        date=args.date,
        environment=args.environment,
        backend=args.backend,
        profile=args.profile,
        workflow_run_url=args.workflow_run_url,
        artifact_location=args.artifact_location,
    )
    if args.output:
        Path(args.output).write_text(log_draft, encoding="utf-8")
    else:
        print(log_draft, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
